export const allUsers = [
  { name: 'John Doe', email: 'john.doe@domain', age: 25, total: 100 },
  { name: 'Jane Smith', email: 'jane.smith@domain', age: 30, total: 200 },
  { name: 'Alice Johnson', email: 'alice.johnson@domain', age: 28, total: 150 },
  { name: 'Bob Brown', email: 'bob.brown@domain', age: 35, total: 300 },
  { name: 'Charlie Davis', email: 'charlie.davis@domain', age: 22, total: 50 },
  { name: 'Eve White', email: 'eve.white@domain', age: 29, total: 120 },
  { name: 'Frank Black', email: 'frank.black@domain', age: 40, total: 400 },
  { name: 'Grace Green', email: 'grace.green@domain', age: 32, total: 250 },
  { name: 'Hank Blue', email: 'hank.blue@domain', age: 27, total: 180 },
  { name: 'Ivy Yellow', email: 'ivy.yellow@domain', age: 31, total: 220 },
  { name: 'Jack Red', email: 'jack.red@domain', age: 26, total: 130 },
  { name: 'Kathy Purple', email: 'kathy.purple@domain', age: 33, total: 270 },
  { name: 'Leo Orange', email: 'leo.orange@domain', age: 24, total: 90 },
  { name: 'Mia Pink', email: 'mia.pink@domain', age: 36, total: 350 },
  { name: 'Nina Gray', email: 'nina.gray@domain', age: 23, total: 80 },
  { name: 'Oscar Cyan', email: 'oscar.cyan@domain', age: 38, total: 450 },
  { name: 'Paul Magenta', email: 'paul.magenta@domain', age: 21, total: 70 },
  { name: 'Quinn Teal', email: 'quinn.teal@domain', age: 39, total: 500 },
  { name: 'Rita Indigo', email: 'rita.indigo@domain', age: 34, total: 280 },
  { name: 'Sam Violet', email: 'sam.violet@domain', age: 37, total: 370 },
  { name: 'Tina Brown', email: 'tina.brown@domain', age: 20, total: 60 },
  { name: 'Uma Silver', email: 'uma.silver@domain', age: 41, total: 550 },
  { name: 'Victor Gold', email: 'victor.gold@domain', age: 42, total: 600 },
  ];
